### ISSUE TITLE
QuickMDP model doesn't solve anymore with QMDPSolver

### ISSUE THREAD

**Issue by gnangnan15** [JuliaPOMDP/QuickPOMDPs.jl#15]
I have used QuickMDP previously together with QMPSolver without issues. But now it seems to be broken. I have tested it with the mountaincar model that you provide.

```
mountaincar = QuickMDP(
    function (s, a, rng)        
        x, v = s
        vp = clamp(v + a*0.001 + cos(3*x)*-0.0025, -0.07, 0.07)
        xp = x + vp
        if xp > 0.5
            r = 100.0
        else
            r = -1.0
        end
        return (sp=(xp, vp), r=r)
    end,
    actions = [-1., 0., 1.],
    initialstate = (-0.5, 0.0),
    discount = 0.95,
    isterminal = s -> s[1] > 0.5
)

solver = QMDPSolver()
policy = solve(solver, m)
```

This throws a BoundsError and I have following warning:

>  WARNING: Some requirements may not be shown because a BoundsError was thrown.
For ordered_states(::Union{MDP,POMDP}) (in solve(::ValueIterationSolver, ::Union{MDP,POMDP})):
Note: Missing methods are often due to incorrect importing. You must explicitly import POMDPs functions to add new methods.
Throwing the first exception (from processing solve(::ValueIterationSolver, ::Union{MDP,POMDP}) requirements):

Is there something missing within my model or have there been some changes with requirements?

**Comment by zsunberg** [comment]
Hi @gnangnan15 good question. The discrete-value-iteration-based QMDP algorithm is unable to work on the mountaincar problem because it only has a generative model, and discrete value iteration requires an explicit model (i.e. a transition function that returns a distribution). You would need to create a new mountaincar with discretized dynamics and the `states` and `transition` QuickMDP keywords implemented.

**Comment by zsunberg** [comment]
Now that I look into this, I see that we don't really have a working way to document requirements for solvers... sorry about that

**Comment by gnangnan15** [comment]
Thanks for your help @zsunberg. I just have seen that I have introduced a bug in my model that was actually discretized.
